server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: booking-public
          uri: lb://booking-service
          predicates:
            - Path=/api/booking/**,/api/bookings/**,/api/users/**,/api/user/**

        - id: hotel-public
          uri: lb://hotel-service
          predicates:
            - Path=/api/rooms/**,/api/hotels/**

        - id: block-internal
          uri: no://op
          predicates:
            - Path=/api/internal/**
          filters:
            - SetStatus=404

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
